### ISSUE TITLE
how to get dataset "ml_1m.pkl"

### ISSUE THREAD

**Issue by daizigege** [hengruizhang98/GCMC-Pytorch-dgl#1]
how to get dataset "ml_1m.pkl"

**Comment by hengruizhang98** [comment]
The .pkl file is too big to upload. You can build it using the original dataset provided by https://grouplens.org/datasets/movielens/. 

DGL team also provides its own implementation: https://github.com/dmlc/dgl/tree/master/examples/pytorch/gcmc, in which you do not have to use a preprocessed dataset.

I hope this will be helpful!

**Comment by Prospero9990** [comment]
Can you please share a drive link of pkl file? 
or can you give me information of what's inside the pickle file

**Comment by prosperopapaleo** [comment]
Can you please share a drive link with pkl file?
or can you give me information of what's inside the pickle file

**Comment by hengruizhang98** [comment]
Here is a google drive link for the pkl file: https://drive.google.com/file/d/1368DhPmyvD1L2Gh_rjKoiSqCYDGfNMcf/view?usp=sharing

**Comment by Prospero9990** [comment]
Can you please share other pkl file with rating_pairs for the second construct class? first method doesn't work for me. thanks for your time.

**Comment by hengruizhang98** [comment]
I've created a new link: https://drive.google.com/file/d/1wLq3dkWxxVyymrNlqQLZB4nuj6PEeQlW/view?usp=sharing .
But I do not recommend you try my implementation, because many dgl functions I used are already deprecated. You can refer to: https://github.com/dmlc/dgl/tree/master/examples/pytorch/gcmc. It's a better implementation.

**Comment by yangnianzu0515** [comment]
Hello, this link is invalid. Can you share a new one? Thanks a lot.

**Comment by hengruizhang98** [comment]
> Hello, this link is invalid. Can you share a new one? Thanks a lot.
Can you try DGL's official implementation: https://github.com/dmlc/dgl/tree/master/examples/pytorch/gcmc? I cannot find the .pkl file as well.
